spring:
  application:
    name: takehome

resilience4j.retry:
    configs:
      asyncRetry:
        maxAttempts: 3
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        wait-duration:
          nanos: 100


logging:
  level:
    com:
      org:
        takehome: "DEBUG"


