spring:
  application:
    name: takehome


logging:
  level:
    com:
      org:
        takehome: "DEBUG"
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg %X{X-Correlation-ID}%n"


